stages:
  - test
  - delivery
  - deploy

test-job:
  stage: test
  script:
  - echo "тесты прошли"

delivery-job:
  stage: delivery
  only:
  - main
  script: docker login -p

deploy-job:
  stage: deploy
  when: manual
  only: :
    - main
  script:
    - -ssh server deploy.sh